version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/parser"
    versions:
    - 7.12.11
    - 7.12.15
    - 7.12.16
    - 7.12.17
    - 7.13.11
    - 7.13.12
    - 7.13.13
    - 7.13.15
    - 7.13.4
    - 7.13.9
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.2
    - 5.24.4
    - 5.26.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.32.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: sequelize
    versions:
    - 6.4.0
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.9
  - dependency-name: "@babel/generator"
    versions:
    - 7.12.11
    - 7.12.15
    - 7.12.17
    - 7.13.0
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-flow-comments"
    versions:
    - 7.12.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: inquirer
    versions:
    - 7.3.3
