environment:
  nodejs_version: "10"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --frozen-lockfile
  - yarn lerna bootstrap
  - npx cypress cache path

cache:
  - '%AppData%\npm'
  - '%USERPROFILE%\AppData\Local\Cypress\Cache'

test_script:
  - node --version
  - yarn --version
  - yarn coreTest_win
  - npx cypress version
  - npx cypress verify
  - cd packages
  - cd yawf-demo-project
  - ps: $ServerProcess = Start-Process yarn start -PassThru
  - yarn cypress:run

on_finish:
  - ps: Stop-Process -Id $ServerProcess.Id

build: off
