environment:
  nodejs_version: "10"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i
  - npm run packageInstall
  - npm i -g lerna

test_script:
  - node --version
  - npm --version
  - npm run coreTest

build: off
