environment:
  nodejs_version: "10"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci
  - npm run packageInstall
  - npx cypress cache path

cache:
  - '%AppData%\npm'
  - '%USERPROFILE%\AppData\Local\Cypress\Cache'

test_script:
  - node --version
  - npm --version
  - npm run coreTest
  - npx cypress version
  - npx cypress verify
  - npm run demoTest

build: off
