# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cypress/browsers:node10.16.0-chrome76
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn --frozen-lockfile
      - run: yarn lerna bootstrap
      - run: npx cypress cache path

      - save_cache:
          paths:
            - node_modules
            - .cache/Cypress
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!

      - run: yarn coreTest

      - run: npx cypress version
      - run: npx cypress verify
      - run:
          name: start yawf-demo-project
          command: yarn start
          background: true
          working_directory: packages/yawf-demo-project
      - run:
          name: run cypress
          command: yarn cypress:run
          working_directory: packages/yawf-demo-project
